"""
generate_data.py
-----------------
Generates a synthetic, anonymized DLP (Data Loss Prevention) alert dataset
that mimics the structure of real enterprise cloud security / endpoint
DLP logs described in the project's Discussion Post.

This is SYNTHETIC DATA. No real organizational, employee, or customer
data is used or represented. It is built with realistic statistical
relationships (e.g., higher regex/PII match counts and poor destination
reputation correlate with higher risk) so that the downstream ML pipeline
has genuine signal to learn from, rather than pure noise.

Each alert is attributed to a real user from the roster generated by
`generate_users.py` (data/raw/users.csv). A user's stable traits
(baseline risk propensity, watchlist status, department, device type)
carry through to every alert they generate, so a given user's alert
history is internally consistent rather than independently randomized
per row -- this is what powers the Analyst dashboard's "users to review"
queue and the Management dashboard's per-user/per-department rollups.

Timestamps span a configurable historical window ending at --today
(default 2026-06-30, matching the project's "current date"), so that
"alerts today" and "alerts year-to-date" are meaningful, non-empty
slices for the live dashboard.

Run:
    python src/generate_data.py --n 100000 --seed 42 \\
        --users data/raw/users.csv --out data/raw/dlp_alerts.csv
"""

import argparse
import numpy as np
import pandas as pd
from datetime import datetime, timedelta


# --------------------------------------------------------------------------
# Reference value pools (mimic real DLP/UEBA categorical fields)
# --------------------------------------------------------------------------

EVENT_TYPES = [
    "email_exfil", "usb_transfer", "cloud_upload", "print_job",
    "clipboard_copy", "web_upload", "removable_media", "screen_capture",
]

POLICY_NAMES = [
    "PCI-DSS_CardData", "PII_SSN_Match", "Source_Code_Exfil",
    "HR_Confidential", "Financial_Records", "Customer_PII",
    "Healthcare_PHI", "Credentials_Leak", "Generic_Confidential",
]

DEST_CATEGORIES = [
    "corporate_approved", "personal_cloud_storage", "webmail",
    "unknown_external", "competitor_domain", "file_sharing_service",
    "social_media", "pastebin_code_sharing",
]

# Reputation score ranges per destination category (lower = worse reputation)
DEST_REPUTATION_RANGES = {
    "corporate_approved": (85, 100),
    "personal_cloud_storage": (40, 70),
    "webmail": (35, 65),
    "unknown_external": (5, 35),
    "competitor_domain": (0, 15),
    "file_sharing_service": (30, 60),
    "social_media": (20, 50),
    "pastebin_code_sharing": (0, 20),
}

TIME_OF_DAY_BUCKETS = ["business_hours", "after_hours", "weekend", "overnight"]


def _dest_weights():
    w = np.array([0.40, 0.16, 0.14, 0.10, 0.04, 0.08, 0.05, 0.03])
    return w / w.sum()


def _sample_destination_reputation(rng, dest_categories):
    """Vectorized: sample a reputation score per row given its dest category."""
    lo = np.array([DEST_REPUTATION_RANGES[c][0] for c in dest_categories])
    hi = np.array([DEST_REPUTATION_RANGES[c][1] for c in dest_categories])
    vals = rng.normal((lo + hi) / 2, (hi - lo) / 5)
    return np.clip(vals, 0, 100).astype(int)


def load_users(users_path):
    users = pd.read_csv(users_path)
    required = {"user_id", "full_name", "department", "primary_device_type",
                "on_watchlist", "baseline_risk_propensity"}
    missing = required - set(users.columns)
    if missing:
        raise ValueError(f"users.csv is missing required columns: {missing}")
    return users


def generate_dataset(n=100000, seed=42, users_path="data/raw/users.csv",
                      today=None, history_days=365):
    """
    Generates n synthetic DLP alert rows, vectorized with numpy for
    efficiency at 100k+ scale, with each alert attributed to a user
    drawn from the roster at users_path.
    """
    rng = np.random.default_rng(seed)
    users = load_users(users_path)
    n_users = len(users)

    if today is None:
        today = datetime(2026, 6, 30, 17, 45)  # treat "now" as late afternoon today
    start_date = today - timedelta(days=history_days)

    # --- Assign each alert to a user ----------------------------------------
    # Alert volume per user is uneven (some users trigger far more alerts
    # than others), weighted loosely by baseline risk propensity so
    # higher-propensity users also tend to generate more alerts overall,
    # not just riskier ones.
    user_weights = (users["baseline_risk_propensity"].to_numpy() + 0.15)
    user_weights = user_weights / user_weights.sum()
    user_idx = rng.choice(n_users, size=n, p=user_weights)

    user_id = users["user_id"].to_numpy()[user_idx]
    department = users["department"].to_numpy()[user_idx]
    device_type = users["primary_device_type"].to_numpy()[user_idx]
    user_on_watchlist = users["on_watchlist"].to_numpy()[user_idx]
    user_propensity = users["baseline_risk_propensity"].to_numpy()[user_idx]

    # --- Per-alert categorical features --------------------------------------
    event_type = rng.choice(EVENT_TYPES, size=n)
    policy_name = rng.choice(POLICY_NAMES, size=n)
    dest_category = rng.choice(DEST_CATEGORIES, size=n, p=_dest_weights())
    time_bucket = rng.choice(TIME_OF_DAY_BUCKETS, size=n, p=[0.65, 0.20, 0.10, 0.05])

    # --- Core numeric features (vectorized) -----------------------------------
    destination_reputation = _sample_destination_reputation(rng, dest_category)

    regex_match_count = (rng.poisson(lam=2, size=n) +
                          (rng.random(n) < 0.15) * rng.integers(8, 25, size=n)).astype(int)

    payload_size_kb = np.round(rng.lognormal(mean=4.0, sigma=1.6, size=n), 2)
    payload_size_kb = np.minimum(payload_size_kb, 500000)

    # Historical user violation frequency now derives from the user's
    # stable baseline propensity (consistent across that user's alerts)
    # plus per-event noise, rather than being fully independent per row.
    user_violation_history_90d = np.clip(
        rng.poisson(lam=0.8 + 6 * user_propensity, size=n), 0, 30
    ).astype(int)

    severity_base = (1 + (regex_match_count > 5).astype(int)
                      + (destination_reputation < 30).astype(int)
                      + (payload_size_kb > 50000).astype(int)
                      + (user_violation_history_90d > 5).astype(int))
    event_severity = np.clip(severity_base + rng.integers(-1, 2, size=n), 1, 5).astype(int)

    content_classifier_confidence = np.where(
        regex_match_count <= 5,
        rng.beta(2, 2, size=n),
        rng.beta(5, 1.5, size=n),
    )
    content_classifier_confidence = np.round(np.clip(content_classifier_confidence, 0, 1), 3)

    # Per-alert watchlist flag mirrors the user's roster status (with a
    # tiny chance of a one-off flag even for non-watchlisted users, e.g.
    # a new HR case opened the same day).
    on_watchlist = np.where(
        user_on_watchlist == 1, 1, (rng.random(n) < 0.01).astype(int)
    ).astype(int)

    is_sanctioned_destination = np.where(
        dest_category == "corporate_approved", 1, (rng.random(n) < 0.05).astype(int)
    ).astype(int)

    hours_since_last_user_alert = np.round(rng.exponential(scale=72, size=n), 1)

    high_risk_extension_prob = np.where(
        np.isin(event_type, ["usb_transfer", "removable_media", "web_upload"]),
        0.35, 0.12
    )
    high_risk_file_extension = (rng.random(n) < high_risk_extension_prob).astype(int)

    # --- Timestamps -------------------------------------------------------
    # Spread across the historical window, with a deliberate uptick in
    # density on recent days (including today) so the Management
    # dashboard's "incidents today" KPI is populated in a realistic way,
    # mimicking growing alert volume over time. days_ago=0 means "today".
    days_ago = (history_days - rng.triangular(
        left=0, mode=history_days, right=history_days, size=n
    )).astype(int)
    days_ago = np.clip(days_ago, 0, history_days)

    hour_offsets = rng.integers(0, 24, size=n)
    minute_offsets = rng.integers(0, 60, size=n)

    today_midnight = today.replace(hour=0, minute=0, second=0, microsecond=0)
    timestamps = []
    for d, h, m in zip(days_ago, hour_offsets, minute_offsets):
        day = today_midnight - timedelta(days=int(d))
        # Cap "today" events at the current hour so we never generate
        # alerts in the future relative to `today`.
        if d == 0:
            h = min(int(h), today.hour)
            if h == today.hour:
                m = min(int(m), today.minute)
        timestamps.append(day + timedelta(hours=int(h), minutes=int(m)))

    # --------------------------------------------------------------------
    # Latent "true risk" score drives the label probabilistically.
    # Now also incorporates the user's stable baseline_risk_propensity,
    # so risk is concentrated in a subset of users rather than uniformly
    # spread across the population -- consistent with insider-threat
    # research and with what the Analyst dashboard needs to be useful
    # (a short list of consistently risky users to review, not noise).
    # --------------------------------------------------------------------
    risk_score = (
        0.18 * (regex_match_count / 25)
        + 0.16 * ((100 - destination_reputation) / 100)
        + 0.12 * np.minimum(payload_size_kb / 100000, 1.0)
        + 0.12 * np.minimum(user_violation_history_90d / 15, 1.0)
        + 0.09 * (event_severity / 5)
        + 0.08 * on_watchlist
        + 0.05 * high_risk_file_extension
        + 0.05 * content_classifier_confidence
        + 0.20 * user_propensity
        - 0.10 * is_sanctioned_destination
    )
    risk_score = np.clip(risk_score + rng.normal(0, 0.06, size=n), 0, 1)

    # Continuous model-style probability used by the dashboard's Analyst
    # view to rank "alerts to review" -- distinct from the hard label
    # below, mirroring how a real classifier would output a calibrated
    # probability rather than a binary decision.
    predicted_risk_probability = np.round(risk_score, 4)

    is_high_risk = (risk_score > 0.34).astype(int)

    alert_id = np.array([f"DLP-{100000 + i}" for i in range(n)])

    df = pd.DataFrame({
        "alert_id": alert_id,
        "timestamp": [t.strftime("%Y-%m-%d %H:%M:%S") for t in timestamps],
        "user_id": user_id,
        "event_type": event_type,
        "policy_name": policy_name,
        "department": department,
        "device_type": device_type,
        "time_of_day_bucket": time_bucket,
        "destination_category": dest_category,
        "destination_reputation_score": destination_reputation,
        "regex_pii_match_count": regex_match_count,
        "payload_size_kb": payload_size_kb,
        "user_violation_history_90d": user_violation_history_90d,
        "event_severity": event_severity,
        "content_classifier_confidence": content_classifier_confidence,
        "on_watchlist": on_watchlist,
        "is_sanctioned_destination": is_sanctioned_destination,
        "hours_since_last_user_alert": hours_since_last_user_alert,
        "high_risk_file_extension": high_risk_file_extension,
        "predicted_risk_probability": predicted_risk_probability,
        "is_high_risk": is_high_risk,  # TARGET LABEL
    })

    return df.sort_values("timestamp").reset_index(drop=True)


def main():
    parser = argparse.ArgumentParser(description="Generate synthetic DLP alert dataset.")
    parser.add_argument("--n", type=int, default=100000, help="Number of alert records to generate.")
    parser.add_argument("--seed", type=int, default=42, help="Random seed for reproducibility.")
    parser.add_argument("--users", type=str, default="data/raw/users.csv",
                         help="Path to the user roster CSV (see generate_users.py).")
    parser.add_argument("--out", type=str, default="data/raw/dlp_alerts.csv", help="Output CSV path.")
    parser.add_argument("--history-days", type=int, default=365,
                         help="Number of days of history to spread alerts across, ending 'today'.")
    args = parser.parse_args()

    df = generate_dataset(n=args.n, seed=args.seed, users_path=args.users,
                           history_days=args.history_days)
    df.to_csv(args.out, index=False)

    print(f"Generated {len(df)} synthetic DLP alert records -> {args.out}")
    print(f"Class balance: {df['is_high_risk'].value_counts(normalize=True).round(3).to_dict()}")
    print(f"Date range: {df['timestamp'].min()} to {df['timestamp'].max()}")
    print(f"Unique users referenced: {df['user_id'].nunique()}")


if __name__ == "__main__":
    main()
